"""initial schema

Revision ID: 2c526581025c
Revises: 
Create Date: 2026-09-01 16:05:40.956105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c526581025c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_whatsapp_number'), 'users', ['whatsapp_number'], unique=True)
    op.create_table('agent_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_messages_user_date', 'agent_messages', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_messages_created_at'), 'agent_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_messages_user_id'), 'agent_messages', ['user_id'], unique=False)
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('mood', sa.String(length=50), nullable=True),
    sa.Column('hunger_level', sa.Integer(), nullable=True),
    sa.Column('sleep_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('water_liters', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkins_created_at'), 'checkins', ['created_at'], unique=False)
    op.create_index(op.f('ix_checkins_user_id'), 'checkins', ['user_id'], unique=False)
    op.create_table('exercise_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_type', sa.String(length=80), nullable=False),
    sa.Column('exercises', sa.JSON(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('perceived_effort', sa.Integer(), nullable=True),
    sa.Column('pain_report', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_logs_logged_at'), 'exercise_logs', ['logged_at'], unique=False)
    op.create_index(op.f('ix_exercise_logs_user_id'), 'exercise_logs', ['user_id'], unique=False)
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('opcao', sa.String(length=1), nullable=True),
    sa.Column('calories', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('carbs_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('logged_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_meals_user_date', 'meals', ['user_id', 'logged_at'], unique=False)
    op.create_index(op.f('ix_meals_logged_at'), 'meals', ['logged_at'], unique=False)
    op.create_index(op.f('ix_meals_user_id'), 'meals', ['user_id'], unique=False)
    op.create_table('plan_nutrition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tdee', sa.Integer(), nullable=False),
    sa.Column('meta_kcal', sa.Integer(), nullable=False),
    sa.Column('meta_p', sa.Integer(), nullable=False),
    sa.Column('meta_f', sa.Integer(), nullable=False),
    sa.Column('meta_c', sa.Integer(), nullable=False),
    sa.Column('meta_agua_ml', sa.Integer(), nullable=False),
    sa.Column('refeicoes_meta', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('plan_training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('protocolo', sa.JSON(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###

    # Seed do usuário original (Michael) — espelha db/schema.sql, mantido
    # para quem já dependia desse bootstrap automático.
    op.execute(
        """
        INSERT INTO users (whatsapp_number, name, age, sex, height_cm, weight_kg, goal)
        VALUES ('553199674109', 'Michael Cruz', 33, 'M', 180, 93,
                'recomposição corporal (perder ~8kg de gordura + ganhar massa magra)')
        ON CONFLICT (whatsapp_number) DO NOTHING
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_training')
    op.drop_table('plan_nutrition')
    op.drop_index(op.f('ix_meals_user_id'), table_name='meals')
    op.drop_index(op.f('ix_meals_logged_at'), table_name='meals')
    op.drop_index('idx_meals_user_date', table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_exercise_logs_user_id'), table_name='exercise_logs')
    op.drop_index(op.f('ix_exercise_logs_logged_at'), table_name='exercise_logs')
    op.drop_table('exercise_logs')
    op.drop_index(op.f('ix_checkins_user_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_created_at'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_agent_messages_user_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_created_at'), table_name='agent_messages')
    op.drop_index('idx_agent_messages_user_date', table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_users_whatsapp_number'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
